### ISSUE TITLE
add the script used for the final video ?

### ISSUE THREAD

**Issue by jdeantoni** [montoyadamien/cineditorml#2]
Unfortunately I cannot find the script used for the final video

**Comment by montoyadamien** [comment]
Hi, the script for the final video is located on "cineditorml.program.scenarios/final_cut.space"

**Comment by PERES-Richard** [comment]
https://github.com/montoyadamien/cineditorml/blob/4d259cb89c2a233c25128e697ffd31029b7e9e13/cineditorml.program.scenarios/final_cut.space#L1
