### ISSUE TITLE
Fade out effect since strangemy positionned on the timeline

### ISSUE THREAD

**Issue by jdeantoni** [montoyadamien/cineditorml#7]
is it normal that the fade out effect on the final_cut example is at the beginning of the timeline ?

**Comment by montoyadamien** [comment]
For this point we thought about two points (but we did not had the time to implement it) :
- removing the transition effect to do not make it appears in timeline
- loop through every elements the effect is applied and display the effect on each element but we did not have the time for that, I will try to do that

**Comment by montoyadamien** [comment]
Hi, we updated the generation code, it's now adding effect on each element :)
