### ISSUE TITLE
paths to video from the scripts are not modified in the generated code

### ISSUE THREAD

**Issue by jdeantoni** [montoyadamien/cineditorml#8]
Since the code is generated in the src-gen sub folder, the paths to the assets is either wrong in the script or in the generated code

**Comment by montoyadamien** [comment]
Since the python code is generated under src-gen, we need to specify the path from the src-gen folder to the assets, in order to have the good paths in the python code :)

**Comment by jdeantoni** [comment]
ok but then it is wrong in the script.... it seems easy to add "../" on all paths during generation, did I miss something ?

**Comment by montoyadamien** [comment]
Hum, because you can put your assets wherever you want yes you can add any path you want :o
